CREATE TABLE VOICE_SESSIONS (
    ID INT,
    AMOUNT VARCHAR(255) NOT NULL,
    SESSION_ID VARCHAR(255) NOT NULL UNIQUE,
    DIRECTION VARCHAR(255) NOT NULL,
    DESTINATION_NUMBER VARCHAR(255) NOT NULL,
    CALL_STATUS VARCHAR(255) NOT NULL,
    DURATION_SECONDS VARCHAR(255) NOT NULL,
    CALL_SESSION_STATE VARCHAR(255) NOT NULL,
    CALLER_NUMBER VARCHAR(255) NOT NULL
)